### ISSUE TITLE
Problem on 03b_finetune_MOBILENETV2_flowers5

### ISSUE THREAD

**Issue by steveice** [GoogleCloudPlatform/practical-ml-vision-book#3]
I run this python notebook on Colab environment. 
However, on the third block it showed 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-63ce862177a9> in <module>()
      1 get_ipython().system('pip install --user --quiet keras-adamw')
      2 os.environ['TF_KERAS'] = '1' # for AdamW
----> 3 from keras_adamw import AdamW

ModuleNotFoundError: No module named 'keras_adamw'
---------------------------------------------------------------------------

**Comment by phycoding** [comment]
!pip install --user --quiet keras-adamw
os.environ['TF_KERAS'] = '1' # for AdamW
from keras_adamw import AdamW


run the above code ... hope you will not get any error
