### ISSUE TITLE
chapter 4: object detection: ModuleNotFoundError: No module named 'cloud_tpu'

### ISSUE THREAD

**Issue by IamExperimenting** [GoogleCloudPlatform/practical-ml-vision-book#4]
Hi @lakshmanok, 

Firstly, thanks for releasing the book, it's really helpful to understand the concepts of vision applications. Currently, I'm working on object detection chapter. I have cloned the repository and trying to replicate the same. But unfortunately, I'm getting this error,
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-e0ad62b2adca> in <module>()
     10 from official.vision.beta.configs import retinanet as retinanet_cfg
     11 from official.vision.beta.configs import backbones as backbones_cfg
---> 12 from official.vision.beta.serving import export_saved_model_lib
     13 from official.core import train_lib
     14 

1 frames
/usr/local/lib/python3.7/dist-packages/official/vision/beta/serving/detection.py in <module>()
     18 import tensorflow as tf
     19 
---> 20 from cloud_tpu.models.detection.utils import box_utils
     21 from official.vision.beta import configs
     22 from official.vision.beta.modeling import factory

ModuleNotFoundError: No module named 'cloud_tpu'
```

 I have also tried "pip install cloud-tpu-client" but still its same.

Could you please help me.  I'm executing this "04ab_retinanet_arthropods_train.ipynb" file. 

Even I have tried in the colab still its the same.

**Comment by IamExperimenting** [comment]
@martin-gorner could you please provide solution to this problem?

**Comment by takumiohym** [comment]
Hi @IamExperimenting,
Could you try to set the version of tf-models-official to v2.5.0?
`!pip install tf-models-official==2.5.0`

**Comment by IamExperimenting** [comment]
@takumiohym it worked thanks 😊
